### ISSUE TITLE
"File System for SMB/CIFS and Windows" should be splitted for two

### ISSUE THREAD

**Issue by AndreyLavrov** [yoichiro/chromeos-filesystem-cifs#102]
@yoichiro your SMB app is great but I think that it needs some rebranding.
For now you has following two brand lines:
1) File System for <Some OS or Cloud Resource>
"File System for Dropbox"
"File System for OneDrive"
2) <Some protocol> File System
"SFTP File System"
"WebDAV File System"
Regular users knows meaning of the first brand line only and only IT professionals knows what protocols are meaning for. I think that less than 5% of Windows users knows that their files are stored in SMB folders.
To attract more users for your applications I suggest you to split current SMB app to two apps with the following names:
"File System for Windows"
"SMB File System"
Those apps can use totally the same code internally but in the future "File System for Windows" app could include "new" Microsoft SAML Server for authentication and SharePoint folders interface.
"SMB File System" could stay clear (without Microsoft aware extensions).
If you are planning to split the SMB App then I suggest to keep statistic (inheritance) for SMB/CIFS App for new "SMB File System" application and publish "File System for Windows" like a totally new app (don't forget to change an icon to Windows four's glass window).﻿

**Comment by yoichiro** [comment]
@AndreyLavrov Hmm... I also think that the two categories "Could/OS" and "Protocol" are correct. However, I cannot agree to separate this SMB app to two apps. Actually, the words "SMB" and "CIFS" looks difficult as most users. That is, I think that I should change this app name to "File System for Windows(R)" to be more simply and clearly. In the other hand, the "SMB File System" is unnecessary, I think. Because, if there is a user who want to mount him/her Samba server, I think the user knows that the SMB protocol is used to mount the Samba server and the protocol is used by Windows OS. That is, the user can find the "File System for Windows(R)" app to mount the Samba server, I guess.

What is a reason you thought you should create the "SMB File System" app as a new app?

Anyway, I'm very glad that you suggested your idea to me. :)

**Comment by AndreyLavrov** [comment]
I have suggested to change name for two reasons:
1) To simplify names for regular users
2) To split apps for future improvements (specialisation)
I think that "File System for Windows" would be great for achieving the first aim. 
The second aim may be on hold while you don't implement much Windows specific features (especially non standard features).
P.S. Why you use "(R)" sign after the name? It's looks weird. Is there a strict guideline that require it in all application names?

**Comment by yoichiro** [comment]
I intend to release a new version including changing the name and icons:
https://github.com/yoichiro/chromeos-filesystem-cifs/pull/127/files

**Comment by yoichiro** [comment]
I just released the new version 2.3.0. In this version, the application name has been changed to "File System for Windows" and all icons have been changed.
Well, I don't intend to release the "SMB/CIFS File System" as a new application, because I don't have any reason to release it...
