### ISSUE TITLE
Chrome OS install plugin fail

### ISSUE THREAD

**Issue by Kleinast** [yoichiro/chromeos-filesystem-cifs#110]
I can't install this plugin on my chrome OS file manager.
When I click on install plugin, I have an alert windows tell me, install fail.

**Comment by hottool77** [comment]
can't install , me too.
when add this software at web store, error  "chrome 45 is required" in japanese.

**Comment by yoichiro** [comment]
@Kleinast @hottool77 Probably, you are using ChromeOS 44 on your Chromebook. I implemented a new feature (auto-updating file list) which a new event supported by ChromeOS 45 was used in the previous version 2.0.3, therefore, your ChromeOS rejected installing my app. So, I just released a new version 2.0.4 including the diff #111 so that my app works on ChromeOS 44. I would be great if you could check whether or not you can install and work my app on your environment.

**Comment by yoichiro** [comment]
I close this issue, because I think this issue has been fixed. Thank you for the reporting.
