### ISSUE TITLE
NT_STATUS_LOGON_FAILURE connecting to Win 7 shares

### ISSUE THREAD

**Issue by BrantleyHobbs** [yoichiro/chromeos-filesystem-cifs#134]
Trying to mount shares on my Windows 7 Pro workstation.  When I manually type in the correct connection information on my Chromebook, I get:

ATTEMPTING TO MOUNT
c000006d NT_STATUS_LOGON_FAILURE

I also cannot browse and enumerate any machines.  I am not part of a domain; I am using local accounts only.  Network discovery is enabled on the Windows machine, and the shares work perfectly fine from Windows, Macs and Linux machines.  I have verified multiple times that I am entering the proper account credentials and machine information.

I have tried enabling the log features on the Chromebook, but I can't find them; I'm running in developer mode and did not see anything in /var/logs.

Chromebook info:
Version 45.0.2454.98
Platform 7262.57.0 (Official Build) stable-channel nyan_blaze
Firmware Google_Nyan_Blaze.5771.63.0

**Comment by BrantleyHobbs** [comment]
Nothing?  Man, just tell me where the logs are and I'll go look for myself....

**Comment by yoichiro** [comment]
@BrantleyHobbs I'm sorry for delay, because I was checking other issue. Well, I need to know the detail of the situation. It would be great if you can collect some information/logs by the following steps:

https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

If you also can capture packets both packets from my app and packets from your Windows/Linux/mac by the following steps, the possobolity to fix this issue will be increasing:

https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-capture-packets-with-Wireshark

**Comment by BrantleyHobbs** [comment]
I will get that and get back to you.  Thanks!

**Comment by yoichiro** [comment]
@BrantleyHobbs I found a bug regarding authentication. See the following post for more detail: https://plus.google.com/u/0/+YoichiroTanaka/posts/EEJyicfnSqK I have already released a new version 2.4.0 including code to fix the problem.

I'm not sure that this version can solve this problem, but could you confirm whether the new version 2.4.0 works on your environment?

**Comment by BrantleyHobbs** [comment]
How do I go about installing the new version?  I'm very new to Chromeos, but I am very familiar with Linux, and have my chromebook in dev mode.

**Comment by yoichiro** [comment]
@BrantleyHobbs Usually, all apps and extensions are updated automatically. You can check each version number on chrome://extensions/ If this app's version number is 2.4.0, it is latest version.

**Comment by BrantleyHobbs** [comment]
That worked!  Thanks!
