### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by nabilh2020** [yoichiro/chromeos-filesystem-cifs#148]
It used to work for me, now it freezes File Manager, and I have to close it to be able to navigate.

I can see one level of directory on mounted volume, but trying to open any lower folder and I get: Some operations are getting longer... abort then I cannot use File Manager until I restart it.

Please fix this :(

**Comment by yoichiro** [comment]
@nabilh2020 Unfortunately, I cannot start to fix your issue because your comment didn't include information to find the reason. Could you post the debug log here which the you face the issue by the following steps: https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
@nabilh2020 I close this issue because you did not provide any information to fix this issue. You can repoen this issue when you can get the logs and other valuable information. Thank you for the reporting.
