### ISSUE TITLE
samsung chromebook2 13 mount  ok,but some file size is negative

### ISSUE THREAD

**Issue by armgong** [yoichiro/chromeos-filesystem-cifs#64]
samsung chromebook2 13 mount  linux samba ok, but some file size is negative.  my chromeos version

version 43.0.2357.125
platform 6946.58.0 (Official Build) stable-channel peach_pi-freon
firmware Google_Peach_Pi.4482.94.0

in the screenshot , console file size is mount use divx118/cifs it show right size ,but in file.app some file size is wrong
![screenshot 2015-06-22 at 20 18 17](https://cloud.githubusercontent.com/assets/4819374/8281577/f1a03dba-191b-11e5-8fa4-209ee46d4cea.png)

**Comment by yoichiro** [comment]
@armgong Probably, the current version of this app can't treat a file size over 2GB.

**Comment by armgong** [comment]
will this solve in short term?

**Comment by yoichiro** [comment]
@armgong Really? Hmm... I didn't modify anything against this issue... Anyway, it is good news to me. :P

**Comment by armgong** [comment]
the only difference is I update chromeos to  43.0.2357.130,maybe this?

**Comment by armgong** [comment]
oh, sorry ,I made mistake, it is mount by mountcifs not your app.

**Comment by dkewley** [comment]
@yoichiro: I successfully used your SMB extension to write a 1GB file to my Synology DS213j NAS (running Samba 4.1.18), but a file that was slightly larger than 2GB had problems.

It appears that the 2+GB file was written correctly up to 2GB+44kB, but then the remainder of the file (about 460kB) was written at an offset of about 6GB into the file (thereby making a sparse file in the underlying ext4 file system on the NAS).

I haven't tested thoroughly enough to state confidently that the problem is with your extension rather than with the NAS or some other piece. But I wanted to ask: Have you had success uploading files >2GB using your SMB extension? Do you have reason to suspect that there might be an issue with the extension? Or would you point me somewhere else as a likely root cause to the misbehavior I saw?

(My scenario was using the ChromeOS Files app to copy files from Google Drive to my NAS using your SMB extension. Since my Chromebook only has 16GB local flash, I don't normally push large files to/from local storage. But it's useful to have my Chromebook manage data transfer between two remote large storage devices/services like my NAS and GDrive. This large transfer appeared to work except for this creation of a hole in the output file.)

**Comment by yoichiro** [comment]
I found a bug in a bit operation logic: https://github.com/yoichiro/chromeos-filesystem-cifs/blob/master/app/scripts/smb_client/types.js#L138
That is, I forgot that JavaScript executes the bit operation as a "32bit" value... I will be able to fix this issue. Please give me a few days.

**Comment by yoichiro** [comment]
@armgong @dkewley I have just released a new version 1.4.5. This version includes the modification to fix this issue. Could you confirm  whether this issue is fixed or not on your environment?

**Comment by armgong** [comment]
fix confirmed,thank your very much

**Comment by dkewley** [comment]
Chrome says I have 1.4.5, but I see the same behavior, and I also see problems with the 2GB file when writing to a share exported by Windows 7. I'll leave this issue closed and open a new one.
